# Site settings
title: Grayscale
email: cameron@cdbdesign.net
url: https://example.github.io
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#095932'

# Footer settings
footer: Cameron Booth

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/coderdaddy
  - title: github
    url: https://github.com/cdb

# Build settings
markdown: kramdown
permalink: pretty
